name: default

on:
  push:
    branches:
    - '*'
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup premake
      uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"
